# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2fc58d5f44b1e9d1f70226703bfaed47ec9e99e4795382c2e7e8f4a6b0aaf76fd67c6e19817865b487f54c4d89ac5b73fa584d492115b8918e8f79854d850f0

test:
  secret_key_base: 0cebbeb6d0db9994d7128fca0d1f1124b4d90d393ef892c5bb9f2a0408629223cbd1909a4c69e038a49014f45e9987a4864198e4b41b0b2c3a928f2f828f58fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
